### PR TITLE
Include the build and prerelease to maintain consistency

### PR DESCRIPTION
**Pull request by danielhuang**

### CODE REVIEW

**Comment by zkat** [comment]
heya. Are you still working on this one? :)

**Comment by danielhuang** [comment]
It's currently being used [here](https://github.com/danielhuang/cotton). The current changes work well enough to serialize/deserialize a version number to/from a string, but I haven't made sure that all cases have been considered.

**Comment by zkat** [comment]
oh hey cool! I didn't know about this project, but it's exactly the kind of project this package was built for, so I'm glad it's being useful :) Happy to take patches if you ever run into all the weird corner cases that I know are out there (there's so many. People's package.jsons are so messy).

**Comment by danielhuang** [comment]
I'd probably leave this as a single change. I'll submit more patches if I notice anything else.

**Comment by zkat** [comment]
@danielhuang I just released this as `node-semver@2.1.0`

**Pull request merged**
